[package]
name = "kool-craft-launcher"
version = "0.0.1"
description = "A Cool Minecraft Launcher"
authors = ["MC_XiaoHei"]
license-file = "LICENSE"
edition = "2021"

[lib]
name = "kcl"
crate-type = ["rlib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.2", features = ["macos-private-api", "unstable"] }
tauri-plugin-shell = "2.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
sys-locale = "0.3"
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-http = { version = "2.3", features = ["stream", "json"] }
tauri-plugin-os = "2.2"
tauri-plugin-store = "2.0"
anyhow = "1.0"
tokio = { version = "1.43", features = ["rt", "rt-multi-thread"] }
futures = "0.3"
zip = "2.2"
tauri-plugin-log = "2.2"
log = "0.4"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
lazy_static = "1.5"
async-trait = "0.1"
uuid = { version = "1.12", features = ["v7", "fast-rng"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-prevent-default = "1.0"
tauri-plugin-single-instance = "2.2"

[target.'cfg(any(target_os = "macos", windows))'.dependencies]
window-vibrancy = "0.5"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
