[package]
name = "kool-craft-launcher"
version = "0.0.1"
description = "A Cool Minecraft Launcher"
authors = ["MC_XiaoHei"]
edition = "2021"

[lib]
name = "tauri_vuetify_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
tauri = { version = "2.2.2", features = ["macos-private-api", "unstable"] }
tauri-plugin-shell = "2.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sys-locale = "0.3.2"
chrono = { version = "0.4.39", features = ["serde"] }
window-vibrancy = "0.5.2"
tauri-plugin-http = "2.2.0"
tauri-plugin-os = "2.2.0"
tauri-plugin-prevent-default = "1.0.1"
tauri-plugin-single-instance = "2.2.1"
tauri-plugin-store = "2.2.0"
rux-downloader = "0.1.0"
