[package]
name = "kool-craft-launcher"
version = "0.0.1"
description = "A Cool Minecraft Launcher"
authors = ["MC_XiaoHei"]
edition = "2021"

[lib]
name = "tauri_vuetify_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
tauri = { version = "2.2.3", features = ["macos-private-api", "unstable"] }
tauri-plugin-shell = "2.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sys-locale = "0.3.2"
chrono = { version = "0.4.39", features = ["serde"] }
tauri-plugin-http = { version = "2.2.0", features = ["stream"] }
tauri-plugin-os = "2.2.0"
tauri-plugin-store = "2.2.0"
anyhow = "1.0.95"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread"] }
futures = "0.3.31"

[target.'cfg(windows)'.dependencies]
window-vibrancy = "0.5.2"
tauri-plugin-prevent-default = "1.0.2"
tauri-plugin-single-instance = "2.2.1"

[target.'cfg(macos)'.dependencies]
window-vibrancy = "0.5.2"
tauri-plugin-prevent-default = "1.0.2"
tauri-plugin-single-instance = "2.2.1"

[target.'cfg(linux)'.dependencies]
tauri-plugin-prevent-default = "1.0.2"
tauri-plugin-single-instance = "2.2.1"

[build]
rustflags = ["-Z", "threads=8"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
