[package]
name = "kool-craft-launcher"
version = "0.0.1"
description = "A Cool Minecraft Launcher"
authors = ["MC_XiaoHei"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tauri_quasar_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
tauri = { version = "2.0.1", features = ["macos-private-api"] }
tauri-plugin-shell = "2.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
window-vibrancy = "0.5.2"
tauri-plugin-http = "2"
tauri-plugin-os = "2"
tauri-plugin-prevent-default = "1.0.1"
tauri-plugin-single-instance = "2"
tauri-plugin-store = "2"
